/* Shared Level 3 content. Keep this file free of page-specific UI code. */
window.Level3Letters = [
  { name: 'Alif',  ar: 'أ', display: 'أَ', forms: ['أَسَدٌ', 'سَأَلَ', 'قَرَأَ'], gameWord: 'أَكَلَ' },
  { name: 'Ba',    ar: 'ب', display: 'بَ', forms: ['بَابٌ', 'كَبِيرٌ', 'كِتَابٌ'], gameWord: 'بَابٌ' },
  { name: 'Ta',    ar: 'ت', display: 'تَ', forms: ['تَمْرٌ', 'فَتَحَ', 'بِنْتٌ'], gameWord: 'تَمْرٌ' },
  { name: 'Tha',   ar: 'ث', display: 'ثَ', forms: ['ثَوْبٌ', 'مَثَلٌ', 'حَدِيثٌ'], gameWord: 'ثَوْبٌ' },
  { name: 'Jeem',  ar: 'ج', display: 'جَ', forms: ['جَمَلٌ', 'شَجَرَةٌ', 'ثَلْجٌ'], gameWord: 'جَمَلٌ' },
  { name: 'Haa',   ar: 'ح', display: 'حَ', forms: ['حُوتٌ', 'بَحْرٌ', 'مِفْتَاحٌ'], gameWord: 'حُوتٌ' },
  { name: 'Khaa',  ar: 'خ', display: 'خَ', forms: ['خُبْزٌ', 'يَخْرُجُ', 'شَيْخٌ'], gameWord: 'خُبْزٌ' },
  { name: 'Dal',   ar: 'د', display: 'دَ', forms: ['دَارٌ', 'مَدْرَسَةٌ', 'وَلَدٌ'], gameWord: 'دَارٌ' },
  { name: 'Thal',  ar: 'ذ', display: 'ذَ', forms: ['ذَهَبٌ', 'مَذْهَبٌ', 'أَخَذَ'], gameWord: 'ذَهَبٌ' },
  { name: 'Ra',    ar: 'ر', display: 'رَ', forms: ['رَجُلٌ', 'مَرَضٌ', 'قَمَرٌ'], gameWord: 'رَجُلٌ' },
  { name: 'Zay',   ar: 'ز', display: 'زَ', forms: ['زَهْرَةٌ', 'مَزْرَعَةٌ', 'خُبْزٌ'], gameWord: 'زَهْرَةٌ' },
  { name: 'Seen',  ar: 'س', display: 'سَ', forms: ['سَمَكٌ', 'مَسْجِدٌ', 'شَمْسٌ'], gameWord: 'سَمَكٌ' },
  { name: 'Sheen', ar: 'ش', display: 'شَ', forms: ['شَمْسٌ', 'مَشْرُوبٌ', 'عَرْشٌ'], gameWord: 'شَمْسٌ' },
  { name: 'Saad',  ar: 'ص', display: 'صَ', forms: ['صَبْرٌ', 'مَصْدَرٌ', 'قِصَصٌ'], highlightOccurrences: [0, 0, 1], gameWord: 'صَبْرٌ' },
  { name: 'Dad',   ar: 'ض', display: 'ضَ', forms: ['ضَيْفٌ', 'مَضْرِبٌ', 'بَيْضٌ'], gameWord: 'ضَيْفٌ' },
  { name: 'Taa',   ar: 'ط', display: 'طَ', forms: ['طَعَامٌ', 'مَطَرٌ', 'خَيْطٌ'], gameWord: 'طَعَامٌ' },
  { name: 'Dhaa',  ar: 'ظ', display: 'ظَ', forms: ['ظَرْفٌ', 'مَنْظَرٌ', 'حِفْظٌ'], gameWord: 'ظَرْفٌ' },
  { name: 'Ain',   ar: 'ع', display: 'عَ', forms: ['عَيْنٌ', 'مَعَلِّمٌ', 'شَارِعٌ'], highlightOccurrences: [0, 0, 0], gameWord: 'عَيْنٌ' },
  { name: 'Ghain', ar: 'غ', display: 'غَ', forms: ['غُرْفَةٌ', 'صَغِيرٌ', 'فَرَاغٌ'], gameWord: 'غُرْفَةٌ' },
  { name: 'Fa',    ar: 'ف', display: 'فَ', forms: ['فَمٌ', 'مَفْتَاحٌ', 'خَرُوفٌ'], gameWord: 'فَمٌ' },
  { name: 'Qaf',   ar: 'ق', display: 'قَ', forms: ['قَلَمٌ', 'بَقَرَةٌ', 'طَرِيقٌ'], gameWord: 'قَلَمٌ' },
  { name: 'Kaf',   ar: 'ك', display: 'كَ', forms: ['كَلْبٌ', 'مَكْتَبٌ', 'شَبَكٌ'], gameWord: 'كَلْبٌ' },
  { name: 'Lam',   ar: 'ل', display: 'لَ', forms: ['لَبَنٌ', 'قَلَمٌ', 'جَمَلٌ'], gameWord: 'لَبَنٌ' },
  { name: 'Meem',  ar: 'م', display: 'مَ', forms: ['مَاءٌ', 'سَمَكٌ', 'عَلَمٌ'], gameWord: 'مَاءٌ' },
  { name: 'Nun',   ar: 'ن', display: 'نَ', forms: ['نَارٌ', 'جَنَّةٌ', 'لَوْنٌ'], gameWord: 'نَارٌ' },
  { name: 'Ha',    ar: 'ه', display: 'هَ', forms: ['هَوَاءٌ', 'مَهْدٌ', 'وَجْهٌ'], gameWord: 'هَوَاءٌ' },
  { name: 'Waw',   ar: 'و', display: 'وَ', forms: ['وَرَقٌ', 'نَوْمٌ', 'دَلْوٌ'], gameWord: 'وَرَقٌ' },
  { name: 'Ya',    ar: 'ي', display: 'يَ', forms: ['يَدٌ', 'بَيْتٌ', 'كُرْسِيٌّ'], gameWord: 'يَدٌ' }
];
